language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install codecov
  - python setup.py install
  - rm -r metalearn

script:
  - nosetests -s -v --with-coverage --cover-package=metalearn
  - codecov
