language: python
python:
  - "3.6"

install:
  - pip install mypy
  - pip install -r requirements.txt


script:
  - mypy .
  # Run tests with the installed version of the code only
  - python setup.py install
  - rm -r metalearn
  - nosetests -s -v
