language: python
python:
  - "3.6"

# - pip install coverage
install:
  - python setup.py install

#  --with-coverage --cover-package=gama
script:
  - nosetests -s -v

#after_success:
# - bash <(curl -s https://codecov.io/bash)