language: python
python:
  - "3.6"

install:
  - pip install mypy
  - pip install codecov
  - pip install -r requirements.txt
  - python setup.py install

script:
  - mypy .
  # Run tests with the installed version of the code only
  - rm -r metalearn
  - nosetests -s -v --with-coverage --cover-package=metalearn
  - codecov
